/*
 * GroupPasswordDecrypterView.java
 */

package com.neohapsis.grouppassworddecrypter;

import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The application's main frame.
 */
public class GroupPasswordDecrypterView extends FrameView {

    public GroupPasswordDecrypterView(SingleFrameApplication app) {
        super(app);

        initComponents();
        this.getFrame().setMinimumSize(this.mainPanel.getPreferredSize());
        this.getFrame().setMaximumSize(this.mainPanel.getPreferredSize());
        this.getFrame().setPreferredSize(this.mainPanel.getPreferredSize());
        this.getFrame().setResizable(false);

        // status bar initialization - message timeout, idle icon and busy animation, etc
       
        
        


    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ciphertextTextField = new javax.swing.JTextField();
        plaintextTextField = new javax.swing.JTextField();
        decryptButton = new javax.swing.JButton();

        mainPanel.setMaximumSize(new java.awt.Dimension(405, 140));
        mainPanel.setMinimumSize(new java.awt.Dimension(405, 140));
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setPreferredSize(new java.awt.Dimension(405, 140));
        mainPanel.setRequestFocusEnabled(false);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.neohapsis.grouppassworddecrypter.GroupPasswordDecrypterApp.class).getContext().getResourceMap(GroupPasswordDecrypterView.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        ciphertextTextField.setText(resourceMap.getString("ciphertextTextField.text")); // NOI18N
        ciphertextTextField.setName("ciphertextTextField"); // NOI18N

        plaintextTextField.setText(resourceMap.getString("plaintextTextField.text")); // NOI18N
        plaintextTextField.setName("plaintextTextField"); // NOI18N

        decryptButton.setText(resourceMap.getString("decryptButton.text")); // NOI18N
        decryptButton.setName("decryptButton"); // NOI18N
        decryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout mainPanelLayout = new org.jdesktop.layout.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, decryptButton)
                    .add(mainPanelLayout.createSequentialGroup()
                        .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2))
                        .add(18, 18, 18)
                        .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, plaintextTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, ciphertextTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(ciphertextTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(plaintextTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(decryptButton)
                .add(72, 72, 72))
        );

        setComponent(mainPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void decryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptButtonActionPerformed
        try {
            String ciphertext = ciphertextTextField.getText();
            String plaintext = GroupPasswordDecrypter.decrypt(ciphertext);
            plaintextTextField.setText(plaintext);
            // TODO add your handling code here:
            System.out.println(plaintextTextField.getText());
        } catch (Exception ex) {
            Logger.getLogger(GroupPasswordDecrypterView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_decryptButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ciphertextTextField;
    private javax.swing.JButton decryptButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField plaintextTextField;
    // End of variables declaration//GEN-END:variables

 
}
